version: 2
jobs:
  build:
    docker:
      - image: python:3.6.0

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login)
      - run:
          name: "Build & Push Docker Image"
          command: |
            docker build -t $AWS_ECR_URL/test:latest -t $AWS_ECR_URL/test:$CIRCLE_SHA1 .
            docker push $AWS_ECR_URL/test:$CIRCLE_SHA1
